export const deviceConstants = {
    INIT_REQUEST: "USERS_INIT_REQUEST",
    INIT_SUCCESS: "USERS_INIT_SUCCESS",
    INIT_FAILURE: "USERS_INIT_FAILURE",

    READERS_REQUEST: "READERS_LIST_REQUEST",
    READERS_SUCCESS: "READERS_LIST_SUCCESS",
    READERS_FAILURE: "READERS_LIST_FAILURE",
}